%YAML 1.1
---
# CPAC Pipeline Configuration YAML file
# Version 1.8.0
#
# http://fcp-indi.github.io for more info.
#
# Tip: This file can be edited manually with a text editor for quick modifications.

FROM: /data3/cnl/cpac_testing/configs/pipeline_config_blank.yml

pipeline_setup:
  pipeline_name: multi-nuisance

functional_preproc:
  run: On
  slice_timing_correction:
    run: [On]

nuisance_corrections:
  2-nuisance_regression:
    run: [On, Off]

    # switch to Off if nuisance regression is off and you don't want to write out the regressors
    create_regressors: On

    # Select which nuisance signal corrections to apply
    Regressors:

      -  Name: 'strat1'

         Motion:
           include_delayed: true
           include_squared: true
           include_delayed_squared: true

         GlobalSignal:
           summary: Mean

         PolyOrt:
          degree: 2

         Bandpass:
           bottom_frequency: 0.01
           top_frequency: 0.1
           method: default
           
         Censor:
           method: 'Interpolate'
           thresholds:
           - type: 'FD_P'
             value: 0.4
           number_of_previous_trs_to_censor: 1
           number_of_subsequent_trs_to_censor: 2

      -  Name: 'strat2'

         Motion:
           include_delayed: true
           include_squared: true
           include_delayed_squared: false

         Bandpass:
           bottom_frequency: 0.01
           top_frequency: 0.1
           method: AFNI
           
         Censor:
           method: 'SpikeRegression'
           thresholds:
           - type: 'FD_J'
             value: 0.3
           number_of_previous_trs_to_censor: 1
           number_of_subsequent_trs_to_censor: 2
           
      -  Name: 'strat3'

         Motion:
           include_delayed: true
           include_squared: false
           include_delayed_squared: false


         Bandpass:
           bottom_frequency: 0.01
           top_frequency: 0.1
           method: default

         Censor:
           method: 'Zero'
           thresholds:
           - type: 'FD_J'
             value: 0.3
           number_of_previous_trs_to_censor: 1
           number_of_subsequent_trs_to_censor: 2
           
      -  Name: 'strat4'

         GlobalSignal:
           summary: NormMean

         Censor:
           method: 'Kill'
           thresholds:
           - type: 'FD_P'
             value: 0.3
           number_of_previous_trs_to_censor: 0
           number_of_subsequent_trs_to_censor: 3
           
post_processing:
  spatial_smoothing:
    output: ['smoothed', 'nonsmoothed']

